version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tienda_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret_password

  web: # Monolito Django (v1)
    build: .
    command: gunicorn Tienda.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    depends_on:
      - db
    environment:
      - DB_NAME=tienda_db
      - DB_USER=postgres
      - DB_PASSWORD=secret_password
      - DB_HOST=db
      - DB_PORT=5432

  # Microservicio de pagos en Flask (v2)
  pagos_flask:
    build: ./microservicio_pagos
    # El puerto 5000 se expone para pruebas, pero Nginx lo manejará internamente
    ports:
      - "5000:5000"
    depends_on:
      - db

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    depends_on:
      - web
      - pagos_flask # Ahora Nginx espera a que ambos servicios estén listos

volumes:
  postgres_data:
  static_volume: