# 1. Definimos los grupos de servidores (Upstreams)
upstream django_backend {
    server web:8000;
}

upstream flask_backend {
    server pagos_flask:5000;
}

server {
    listen 80;

    # Opcional: Logs y favicon
    location = /favicon.ico { access_log off; log_not_found off; }

    # RUTA PARA ARCHIVOS ESTATICOS (CSS, JS, Imagenes)
    location /static/ {
        alias /app/staticfiles/;
    }


    # 2. RUTA DEL ESTRANGULADOR (v2)
    # Redirigimos específicamente la nueva lógica de pagos al microservicio Flask
    location /api/v2/comprar {
        proxy_pass http://flask_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # 3. RUTA POR DEFECTO (v1)
    # Todo lo que no sea la v2 de pagos sigue yendo al Monolito Django
    location / {
        proxy_pass http://django_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_redirect off;
    }
}