# nginx/nginx.conf

# 1. Definimos nuestro sistema backend (Django + Gunicorn)
# El nombre 'web' debe coincidir con el nombre del servicio en docker-compose
upstream django_backend {
    server web:8000;
}

server {
    # Nginx escuchará en el puerto web estándar (80)
    listen 80;

    # Ignorar logs de favicon para no saturar el servidor
    location = /favicon.ico { access_log off; log_not_found off; }
    
    # 2. Proxy Inverso: Todo el tráfico raíz va al backend de Django
    location / {
        proxy_pass http://django_backend;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    # Nota Arquitectónica: En el futuro, aquí agregaremos una nueva
    # regla 'location /api/v2/' que apuntará a nuestro microservicio Flask
    # para ejecutar el Strangler Pattern.

}