# Generated by Django 5.2.10 on 2026-02-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0002_orden_direccion_envio_orden_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='libro',
        ),
        migrations.AddField(
            model_name='orden',
            name='libros',
            field=models.ManyToManyField(related_name='ordenes', to='tienda_app.libro'),
        ),
    ]
